[package]
name = "timezoner"
description = "a discord bot that makes timezone conversions really easy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
sparkle-convenience = "0.14"
sparkle-cache-postgres = "0.14"
twilight-model = "0.14"
twilight-util = { version = "0.14", features = ["builder"] }
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }
futures = "0.3"
anyhow = "1.0"