[package]
name = "timezoner-discord-bot"
description = "a discord bot that makes timezone conversions really easy"
version = "0.1.0"
repository = "https://github.com/laralove143/timezoner-discord-bot"
keywords = ["discord", "bot", "time"]
categories = ["web-programming::http-client"]
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.16", features = ["macros", "rt-multi-thread"] }
futures = { version = "0.3", default-features = false }
twilight-gateway = { version = "0.9", default-features = false, features = [
    "rustls-native-roots",
    "zlib-simd",
] }
twilight-http = { version = "0.9", default-features = false, features = [
    "decompression",
    "rustls-native-roots",
    "trust-dns",
] }
twilight-model = "0.9"
twilight-cache-inmemory = { version = "0.9", features = ["permission-calculator"] }
twilight-util = { version = "0.9", features = ["builder"] }
twilight-model = "0.9"
twilight-mention = "0.9"
twilight-interactions = "0.9"
sqlx = { version = "0.5", default-features = false, features = [
    "runtime-tokio-rustls",
    "macros",
    "sqlite",
] }
chrono = "0.4"
chrono-tz = "0.6"
anyhow = "1.0"
once_cell = "1.10"
