[package]
name = "timezoner-discord-bot"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
futures = { version = "0.3", default-features = false }
twilight-gateway = { version = "0.7", default-features = false, features = [
    "rustls",
    "simd-json",
    "zlib-simd",
] }
twilight-http = { version = "0.7", default-features = false, features = [
    "rustls",
    "simd-json",
    "decompression",
] }
twilight-model = "0.7"
twilight-util = { version = "0.7", features = ["builder"] }
twilight-mention = "0.7"
sqlx = { version = "0.5", default-features = false, features = [
    "runtime-tokio-rustls",
    "macros",
    "sqlite",
] }
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.6"
