[package]
name = "timezoner"
description = "a discord bot that makes timezone conversions really easy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
sparkle-convenience = "0.14"
sparkle-cache-postgres = "0.14"
twilight-gateway = "0.14"
twilight-model = "0.14"
twilight-interactions = "0.14"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres"]}
time = "0.3"
time-tz = "1.0"
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }
futures = "0.3"
anyhow = { version = "1.0", features = ["backtrace"] }
thiserror = "1.0"